version: '3.4'

services: 
    # It creates the front-end website and names it frontend. The code tells Docker to build it and points to the Stores Dockerfile
    frontend:
        image: storeimage
        build:
            context: .
            dockerfile: ./Store/Dockerfile        
        environment: 
           # # The code sets an environment variable for the website: <ProductEndpoint=http://backend:8080>. This code is how the front-end service finds the Products back-end service
           - ProductEndpoint=http://backend:8080
           # A second environment variable specifies where images for products are located
           - ImagePrefix=http://localhost
        # The code opens a port and declares that it depends on the back-end service
        ports:
           - "32000:8080"
        # The back-end service named <backend> is created next. The same Dockerfile that you created in the previous exercise builds it        
        depends_on: 
           - backend
    backend:
        image: productservice
        build: 
            context: .
            dockerfile: ./Products/Dockerfile
        # The last command specifies which port to open
        ports: 
           - "32001:8080"